# Workflow name.

name: Deploy model to Render

# Run workflow on every push to main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}